<!-- body.phtml -->
<?php
$prefixes = '
PREFIX cphm: <' . $this->namespaces["cphm"] . '>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ';

$personsQuery = $prefixes . 'SELECT DISTINCT ?resourceUri
WHERE {
	?resourceUri <' . $this->namespaces["cphm"] . 'hasPeriod> ?period .
	?period <' . $this->namespaces["cphm"] . 'periodBody> <'.$this->resourceUri.'> .
}';
$persons = $this->querylist( $personsQuery, 'local/items/liplain.phtml');

?>

<h2 class=""><?php echo $this->title ?></h2>

<?php $bodyPlace = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["cphm"] . 'bodyPlace> ?resourceUri', 'template' => 'resource'));
if ( $bodyPlace != "" ) { ?>
	<p>Ort: <?php echo $bodyPlace; ?></p>
<?php } ?>

<?php $isPartOf = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["cphm"] . 'isPartOf> ?resourceUri', 'template' => 'resource'));
if ( $isPartOf != "" ) { ?>
	<p>Gehört zu: <?php echo $isPartOf; ?></p>
<?php } ?>

<?php $faculties = $this->query(array('where' => '?resourceUri <' . $this->namespaces["cphm"] . 'isPartOf> <' . $this->resourceUri . '>', 'template' => 'liplain'));
if ( $faculties != "" ) { ?>
	<div class="">
		<h3 class="">Zugehörige Fakultäten/Isntitute/Bereiche</h3>
		<?php echo $faculties; ?>
	</div>
<?php } ?>

<?php if ( $persons != "" ) { ?>
	<div class="">
		<h3 class="">In Beziehung stehende Personen</h3>
		<?php echo $persons; ?>
	</div>
<?php } ?>

<?php $docs = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["cphm"] . 'documentBody> ?resourceUri', 'template' => 'liplain'));
if ( $docs != "" ) { ?>
	<div class="">
		<h3 class="">In Beziehung stehende Dokumente</h3>
		<?php echo $docs; ?>
	</div>
<?php } ?>