<!-- person.phtml -->

<?php
$prefixes = '
PREFIX cphm: <' . $this->namespaces["cphm"] . '>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> ';

/*
Matrikel */
$matrikelQuery = $prefixes . 'SELECT DISTINCT * WHERE {
	<' . $this->resourceUri . '> cphm:hasMatrikel ?resourceUri .
	?resourceUri cphm:semester ?label .
	}';
$matrikel = $this->querylist( $matrikelQuery, 'local/items/resource.phtml' );
// isProf for Classtype "Matrikel"
$isProfQuery = $prefixes . 'SELECT DISTINCT * WHERE {
	?resourceUri rdf:type cphm:Professor ;
		cphm:hasMatrikel <' . $this->resourceUri . '> .
	}';
$isProf = $this->querylist( $isProfQuery, 'local/items/resource.phtml' );

/*
Birth & Death */
$birthDeathQuery = $prefixes . 'SELECT *
WHERE {
	<' . $this->resourceUri . '> cphm:hasPeriod ?resourceUri .
	?resourceUri rdf:type ?classTypeof .
	{ ?resourceUri rdf:type cphm:Birth . }
	UNION
	{ ?resourceUri rdf:type cphm:Death . }
	OPTIONAL { ?resourceUri cphm:date ?date . }
	OPTIONAL { ?resourceUri cphm:periodNote ?periodNote . }	
} ORDER BY ?date';
//OPTIONAL { ?resourceUri cphm:periodPlace ?periodPlace . }
$birthDeath = $this->querylist( $birthDeathQuery, 'local/items/periodOfLife.phtml', array('cphm' => $this->namespaces["cphm"]));

/*
Family: Parents, Siblings, Spouse, Childs */
$parentsQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?familyUri rdf:type cphm:Family ;
		cphm:familyChild ?child ;
		cphm:familyParent ?resourceUri .
	FILTER ( ?child = <'.$this->resourceUri.'> ) }';
$siblingsQuery = $prefixes . 'SELECT DISTINCT * WHERE {
	?familyUri rdf:type cphm:Family ;
		cphm:familyChild ?resourceUri ;
		cphm:familyChild <' . $this->resourceUri . '> .
	FILTER ( ?resourceUri != <'.$this->resourceUri.'> ) }';
	//FILTER EXISTS { ?familyUri cphm:familyChild <' . $this->resourceUri . '> } }';
$spouseQuery = $prefixes . 'SELECT DISTINCT * WHERE {
	?familyUri rdf:type cphm:Family ;
		cphm:familyParent ?resourceUri ;
		cphm:familyParent <' . $this->resourceUri . '> .
	FILTER ( ?resourceUri != <'.$this->resourceUri.'> ) }';
	//FILTER EXISTS { ?familyUri cphm:familyParent <' . $this->resourceUri . '> . } }';
$childsQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?familyUri rdf:type cphm:Family ;
		cphm:familyChild ?resourceUri ;
		cphm:familyParent ?parent .
	FILTER ( ?parent = <'.$this->resourceUri.'> ) }';

$family = array( 
	"parents" 	=> $this->querylist( $parentsQuery, 'local/items/liplain.phtml', array('mode' => 'parents')),
	"siblings"	=> $this->querylist( $siblingsQuery, 'local/items/liplain.phtml', array('mode' => 'siblings')),
	"spouse" 	=> $this->querylist( $spouseQuery, 'local/items/liplain.phtml', array('mode' => 'spouse')),
	"childs" 	=> $this->querylist( $childsQuery, 'local/items/liplain.phtml', array('mode' => 'childs'))
);
$familyLength = 0;
foreach ($family as $k) { $familyLength += strlen($k); }

/*
Periods of Life ()without Birth,Death,Family
*/
$periodsObjects = array();
$periodsClasses = array( "Qualification", "Chair", "Career", "Office" );
foreach ($periodsClasses as $periodClass) {
	$periodQuery = $prefixes . 'SELECT *
	WHERE {
		<' . $this->resourceUri . '> cphm:hasPeriod ?resourceUri .
		?resourceUri rdf:type ?classTypeof .
		?resourceUri rdf:type cphm:'.$periodClass.' .
		OPTIONAL { ?resourceUri cphm:periodPlace ?periodPlace . }	
		OPTIONAL { ?resourceUri cphm:date ?date . }
		OPTIONAL { ?resourceUri cphm:from ?from . }
		OPTIONAL { ?resourceUri cphm:to ?to . }
		OPTIONAL { ?resourceUri cphm:periodNote ?periodNote . }
		OPTIONAL { 
			?resourceUri cphm:periodDocument ?periodDocument . 
			OPTIONAL {
				?periodDocument rdfs:label ?periodDocumentLabel .
			}
		}
	} ORDER BY ASC(?date) ASC(?from)';
	$periodObject = $this->querylist($periodQuery, 'local/items/periodOfLife.phtml', array('cphm' => $this->namespaces["cphm"]));
	if ( $periodObject != "" ) {
		$periodsObjects[] = array( "key" => $periodClass, "content" => $periodObject );
	}
}

/*
Dissertationen
*/
$praesesQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:QualificationDocument ;
		cphm:praeses ?praeses .
	FILTER ( ?praeses = <'.$this->resourceUri.'> ) }';
$dedicateeeQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:QualificationDocument ;
		cphm:dedicatee ?dedicatee .
	FILTER ( ?dedicatee = <'.$this->resourceUri.'> ) }';
$respondentQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:QualificationDocument ;
		cphm:respondent ?respondent .
	FILTER ( ?respondent = <'.$this->resourceUri.'> ) }';
$gratulantQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:QualificationDocument ;		
		cphm:gratulant ?gratulant .
	FILTER ( ?gratulant = <'.$this->resourceUri.'> ) }';
$dissertation = array(
	"praeses" 	=> $this->querylist( $praesesQuery, 'local/items/liplain.phtml'),
	"dedicatee"	=> $this->querylist( $dedicateeeQuery, 'local/items/liplain.phtml'),
	"respondent"=> $this->querylist( $respondentQuery, 'local/items/liplain.phtml'),
	"gratulant" => $this->querylist( $gratulantQuery, 'local/items/liplain.phtml')
);
$dissertationLength = 0;
foreach ($dissertation as $k) { $dissertationLength += strlen($k); }

/*
Vorlesungen
*/
$courseQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:Course ;
		cphm:lecture ?lecture .
	FILTER ( ?lecture = <'.$this->resourceUri.'> ) }';
$course = $this->querylist( $courseQuery, 'local/items/liplain.phtml' );
/*
Reden und Programme
*/
$thesesQuery = $prefixes . 'SELECT DISTINCT * WHERE { 
	?resourceUri rdf:type cphm:Theses ;
		cphm:author ?author .
	FILTER ( ?author = <'.$this->resourceUri.'> ) }';
$theses = $this->querylist( $thesesQuery, 'local/items/liplain.phtml' );


/*******************************************************************************
END of Queries ....*/
?>

<h2 class=""><?php echo $this->title ?></h2>

<?php $image = $this->literal(array('property' => $this->namespaces["cphm"] . 'imageSource'));
if ( $image != "" ) { ?>
	<p>Proträt: <?php echo $image; ?></p>
<?php } ?>

<?php /* if ( $forenames != "" ) { ?>
	<p>Vornamen: <?php echo $forenames; ?></p>
<?php } */ ?>

<?php $denomination = $this->literal(array('property' => $this->namespaces["cphm"] . 'denomination'));
if ( $denomination != "" ) { ?>
	<p>Konfession: <?php echo $denomination; ?></p>
<?php } ?>

<?php $alternativeWritingOfSurname = $this->literal(array('property' => $this->namespaces["cphm"] . 'alternativeWritingOfSurname'));
if ( $alternativeWritingOfSurname != "" ) { ?>
	<p>Namensvariante: <?php echo $alternativeWritingOfSurname; ?></p>
<?php } ?>

<?php if ( ! empty( $matrikel ) ) { ?>
	<div class="">
		Immatrikulation: <?php echo $matrikel; ?>
	</div>	
<?php } ?>

<?php if ( ! empty( $isProf ) ) { ?>
	<div class="">
		ist Professor: <?php echo $isProf; ?>
	</div>	
<?php } ?>

<?php if ( $birthDeath != "" ) { ?>
	<div class="period-of-life birthDeath">
		<h3 class="">Lebensdaten</h3>
		<?php echo $birthDeath; ?>
	</div>
<?php } ?>

<?php if ( $familyLength > 0 ) { ?>
	<div class="period-of-life family">
		<h3 class="">Familie</h3>
		<?php // $this->_('family') ?>
		<?php
		echo !empty($family["parents"]) ? "<h4>Eltern</h4>" . $family["parents"] : "";
		echo !empty($family["siblings"]) ? "<h4>Geschwister</h4>" . $family["siblings"] : "";
		echo !empty($family["spouse"]) ? "<h4>Partner</h4>" . $family["spouse"] : "";
		echo !empty($family["childs"]) ? "<h4>Kinder</h4>" . $family["childs"] : "";
		?>
	</div>
<?php } ?>

<?php
if ( count( $periodsObjects ) > 1 ) { ?>
	<h3 class="">Lebenslauf</h3>
	<?php foreach ($periodsObjects as $key => $periodObject) { ?>
		<div class="period-of-life period">

			<?php 
			$classTypeof = $prefixes . 'SELECT *
			WHERE {
				<http://http://uni-helmstedt.hab.de/cphm/'.$periodObject["key"].'> rdfs:label ?resourceUri .
				FILTER (lang(?resourceUri) = "de")
			}';
			$classTypeof = $this->querylist( $classTypeof, 'local/items/plain.phtml'); ?>

			<h4><?php echo $classTypeof; ?></h4>
			<table class="table">
				<?php echo $periodObject["content"]; ?>
			</table>
		</div>
	<?php 
	}
} ?>

<?php if ( $dissertationLength > 0 ) { ?>
	<div class="period-of-life dissertation">
		<h3 class="">Dissertationen</h3>
		<?php
		echo !empty($dissertation["respondent"]) ? "<h4>Respondent</h4>" . $dissertation["respondent"] : "";
		echo !empty($dissertation["dedicatee"]) ? "<h4>Dedicatee</h4>" . $dissertation["dedicatee"] : "";
		echo !empty($dissertation["gratulant"]) ? "<h4>Gratulant</h4>" . $dissertation["gratulant"] : "";
		echo !empty($dissertation["praeses"]) ? "<h4>Praeses</h4>" . $dissertation["praeses"] : "";
		?>
	</div>
<?php } ?>

<?php
if ( ! empty($theses) ) {
	echo '<h3 class="">Reden und Programme</h3>';
	echo $theses;
}
if ( ! empty($course) ) {
	echo '<h3 class="">Vorlesungen</h3>';
	echo $course;
}


/*
Weitere Infos
*/
$furtherProperties = array(
	"Publikationen" => "published",	
	"DNB-Link" => "gnd",
	"Autobiografische Literatur" => "literature",
	"Referenzen und Quellen" => "references",
	"Weblinks" => "webLinks",
	"Weitere Informationen" => "furtherInformation",
	"Anmerkung" => "note",

);

foreach ($furtherProperties as $key => $value) {
	$property = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["cphm"] . $value.'> ?resourceUri', 'template' => 'liplain'));
	if ( $property != "" ) {
		echo "<h3>".$key."</h3>";
		echo $property;
	}
} ?>